/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	vhostv1alpha1 "github.com/opslib/crd-nginx-vhost/pkg/apis/vhost/v1alpha1"
	versioned "github.com/opslib/crd-nginx-vhost/pkg/client/clientset/versioned"
	internalinterfaces "github.com/opslib/crd-nginx-vhost/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/opslib/crd-nginx-vhost/pkg/client/listers/vhost/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VhostInformer provides access to a shared informer and lister for
// Vhosts.
type VhostInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.VhostLister
}

type vhostInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVhostInformer constructs a new informer for Vhost type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVhostInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVhostInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredVhostInformer constructs a new informer for Vhost type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVhostInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VhostV1alpha1().Vhosts(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VhostV1alpha1().Vhosts(namespace).Watch(options)
			},
		},
		&vhostv1alpha1.Vhost{},
		resyncPeriod,
		indexers,
	)
}

func (f *vhostInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVhostInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *vhostInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&vhostv1alpha1.Vhost{}, f.defaultInformer)
}

func (f *vhostInformer) Lister() v1alpha1.VhostLister {
	return v1alpha1.NewVhostLister(f.Informer().GetIndexer())
}
